notifications:
  email: false
  irc:
    channels:
      - "irc.mysociety.org#sayit"
    use_notice: true

language: python

services:
  - elasticsearch

env:
  - MODULES="Django>=1.4,<1.5"
  - MODULES="Django>=1.5,<1.6"
  - MODULES="Django>=1.6,<1.7"
  - MODULES="git+https://github.com/django/django.git@master#egg=django"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ffmpeg libavcodec-extra-53 iceweasel xvfb yui-compressor
  - gem install compass zurb-foundation
  - pip install $MODULES
  - pip install -r requirements.txt
  - sed -r -e "s,(SAYIT_DB_USER:) 'sayit',\\1 'postgres'," conf/general.yml-example > conf/general.yml

before_script:
  - psql -c 'create database sayit;' -U postgres
  - ./manage.py syncdb --noinput --migrate
  - compass compile web
  - ./manage.py collectstatic --noinput
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

env:
  - SELENIUM_TESTS=1

script:
  - ./manage.py test
